// 主页
export const TURN_HOME_PAGE = 'TURN_HOME_PAGE'
export const SET_SHADOW_MODE = 'SET_SHADOW_MODE'
export const SET_PIC_POSITION = 'SET_PIC_POSITION'
export const PIC_TURN_SIDE = 'PIC_TURN_SIDE'
export const GET_MUSIC_ITEM = 'GET_MUSIC_ITEM'
export const SET_MOVIE_CUBE = 'SET_MOVIE_CUBE'

